version: 2
jobs:

    build_jessie:
        working_directory: ~/hyperloglog
        docker:
            - image: debian:jessie
        steps:
            - checkout
            - run: apt-get update
            - run: apt-get install -y --no-install-recommends python3 python3-dev python3-venv g++ make
            - run: make check

    build_stretch:
        working_directory: ~/hyperloglog
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run: apt-get update
            - run: apt-get install -y --no-install-recommends python3 python3-dev python3-venv g++ make
            - run: make check

    build_buster:
        working_directory: ~/hyperloglog
        docker:
            - image: debian:buster
        steps:
            - checkout
            - run: apt-get update
            - run: apt-get install -y --no-install-recommends python3 python3-dev python3-venv g++ make
            - run: make check

workflows:
    version: 2
    build_and_test:
        jobs:
            - build_jessie
            - build_stretch
            - build_buster
